# SPDX-FileCopyrightText: 2024 Daniel Biehl <daniel.biehl@imbus.de>
#
# SPDX-License-Identifier: Apache-2.0

log-level = "TRACE"
[env]
PYTHONNET_RUNTIME = "coreclr"
# PYTHONNET_RUNTIME = "netfx"
PYTHONNET_CORECLR_DOTNET_ROOT = "C:\\Users\\daniel\\Downloads\\dotnet-sdk-8.0.302-win-x64"
